sudo: required

services:
  - docker

language: go

script:
  - docker version
  - docker build -t $DOCKER_REGISTRY/pop_deploy .

after_success:
  - >-
   if [ "$TRAVIS_BRANCH" == "master" ]; then
   docker login -u="$DOCKER_USER" -p="$DOCKER_PWD" $DOCKER_REGISTRY;
   docker build -t $DOCKER_REGISTRY/pop_deploy .;
   docker push $DOCKER_REGISTRY/pop_deploy:latest;
   fi


notifications:
  slack: societyco:T1mHeYKrOtopvRjIZ68MqOQo
