version: "3"

networks:
  traefik-net:
    external: true
  database-network:
    external: true

services:
  api:
    image: registry.popcube.xyz:5000/popcubeapi:alpha-1.1.11
    env_file: ${PATH_ENV_FILE:-.env}
    networks:
      - traefik-net
      - database-network
    depends_on:
      - database
    deploy:
      labels:
        traefik.port: "3000"
        traefik.frontend.rule: "Host:${ORGANISATION}.popcube.xyz"
        xyz.popcube.date.created: "${CREATED_DATE}"
        traefik.backend.loadbalancer.sticky: "true"
        traefik.backend.loadbalancer.swarm: "true"
        traefik.docker.network: "traefik-net"
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.40'
          memory: 90M
        reservations:
          cpus: '0.10'
          memory: 10M
  database:
    image: registry.popcube.xyz:5000/popcubedb_base:latest
    env_file: ${PATH_ENV_FILE:-.env}
    networks:
      - database-network
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.90'
          memory: 450M
        reservations:
          cpus: '0.20'
